export const stateNamings = {
  emer: ["emer", "setEmer"],
  transport: ["transport", "setTransport"],
  mbiemer: ["mbiemer", "setMbiemer"],
  email: ["email", "setEmail"],
  phone: ["phone", "setPhone"],
  fjalekalim: ["fjalekalim", "setFjalekalim"],
  emerKompanie: ["emerKompanie", "setEmerKompanie"],
  qytet: ["qytet", "setQytet"],
  zipCode: ["zipCode", "setZipCode"],
  rruga: ["rruga", "setRruga"],
  note: ["note", "setNote"],
};

export const cities = [
  { id: 69, label: "Tirana" },
  { id: 23, label: "Kamëz" },
  { id: 74, label: "Vorë" },
  { id: 12, label: "Durrës" },
  { id: 13, label: "Elbasan" },
  { id: 15, label: "Fier" },
  { id: 29, label: "Korçë" },
  { id: 73, label: "Vlorë" },
  { id: 4, label: "Berat" },
  { id: 20, label: "Gjirokastër" },
  { id: 62, label: "Sarandë" },
  { id: 34, label: "Kuçovë" },
  { id: 35, label: "Kukës" },
  { id: 51, label: "Përmet" },
  { id: 5, label: "Bilisht" },
  { id: 6, label: "Bulqizë" },
  { id: 7, label: "Burrel" },
  { id: 8, label: "Cërrik" },
  { id: 66, label: "Shkodër" },
  { id: 52, label: "Peshkopi" },
  { id: 53, label: "Pogradec" },
  { id: 14, label: "Ersekë" },
  { id: 1, label: "Bajram Curri" },
  { id: 2, label: "Bajzë" },
  { id: 3, label: "Ballsh" },
  { id: 9, label: "Çorovodë" },
  { id: 10, label: "Delvinë" },
  { id: 11, label: "Divjakë" },
  { id: 16, label: "Fierzë" },
  { id: 17, label: "Finiq" },
  { id: 18, label: "Fushë-Arrëz" },
  { id: 19, label: "Fushë-Krujë" },
  { id: 21, label: "Gramsh" },
  { id: 22, label: "Himarë" },
  { id: 24, label: "Kavajë" },
  { id: 25, label: "Këlcyrë" },
  { id: 26, label: "Klos" },
  { id: 27, label: "Konispol" },
  { id: 28, label: "Koplik" },
  { id: 30, label: "Krastë" },
  { id: 31, label: "Krrabë" },
  { id: 32, label: "Krujë" },
  { id: 33, label: "Krumë" },
  { id: 36, label: "Kurbnesh" },
  { id: 37, label: "Laç" },
  { id: 38, label: "Leskovik" },
  { id: 39, label: "Lezhë" },
  { id: 40, label: "Libohovë" },
  { id: 41, label: "Librazhd" },
  { id: 42, label: "Lushnjë" },
  { id: 43, label: "Maliq" },
  { id: 44, label: "Mamurras" },
  { id: 45, label: "Manëz" },
  { id: 46, label: "Memaliaj" },
  { id: 47, label: "Milot" },
  { id: 48, label: "Orikum" },
  { id: 49, label: "Patos" },
  { id: 50, label: "Peqin" },
  { id: 54, label: "Poliçan" },
  { id: 55, label: "Prrenjas" },
  { id: 56, label: "Pukë" },
  { id: 57, label: "Reps" },
  { id: 58, label: "Roskovec" },
  { id: 59, label: "Rrëshen" },
  { id: 60, label: "Rrogozhinë" },
  { id: 61, label: "Rubik" },
  { id: 63, label: "Selenicë" },
  { id: 64, label: "Shëngjin" },
  { id: 65, label: "Shijak" },
  { id: 67, label: "Sukth" },
  { id: 68, label: "Tepelenë" },
  { id: 70, label: "Ulëz" },
  { id: 71, label: "Ura Vajgurore" },
  { id: 72, label: "Vau i Dejës" },
];